// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// battles.js
export const FETCH_BATTLES_SUCCESS = 'FETCH_BATTLES_SUCCESS'
export const FETCH_BATTLES_FAILURE = 'FETCH_BATTLES_FAILURE'
export const FETCH_BATTLE_SUCCESS = 'FETCH_BATTLE_SUCCESS'
export const FETCH_BATTLE_FAILURE = 'FETCH_BATTLE_FAILURE'
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS'
export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE'
export const DELETE_ENTRY = 'DELETE_ENTRY'
export const FETCH_VOTES_SUCCESS = 'FETCH_VOTES_SUCCESS'
export const FETCH_VOTES_FAILURE = 'FETCH_VOTES_FAILURE'

// timezone.js
export const UPDATE_TIMEZONE = 'UPDATE_TIMEZONE'
